# Generated by Django 3.2.4 on 2021-06-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='work',
            field=models.CharField(default='', max_length=300),
        ),
    ]
